[build]
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
